version: '3.8'

services:
  database:
    image: postgres:13.3
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: qwerty
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: exampledb

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080